baseURL = 'https://philmikejones.github.io'
languageCode = 'en-gb'
title = 'Phil Mike Jones'
publishDir = 'docs'
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
